name: rest_admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  logger: ^2.6.1
  flutter_form_builder: ^10.2.0
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  rounded_loading_button_plus: ^3.0.1
  flutter_gradient_animation_text: ^1.0.2
  device_info_plus: ^12.1.0
  syncfusion_flutter_datagrid: ^31.1.19
  syncfusion_flutter_core: ^31.1.19
  get_secure_storage: ^1.0.5
  loading_animation_widget: ^1.3.0
  easy_image_viewer: ^1.5.1
  responsive_grid: ^2.4.4
  popup_menu: ^2.1.0
  image_picker: ^1.2.0
  path: ^1.9.1
  http_parser: ^4.1.2
  mime: ^2.0.0
  flutter_number_pagination: ^0.0.1
  skeletonizer: ^2.1.0+1
  intl: ^0.20.2
  date_field: ^6.0.3+1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  image: ^4.5.4
  permission_handler: ^12.0.1
  flutter_file_saver: ^0.9.0
  flutter_admin_scaffold: ^1.4.0
  font_awesome_flutter: ^10.10.0
  fl_chart: ^1.1.1
  file_picker: ^10.3.3
  flutter_smart_dialog: ^4.9.8+9
  window_manager: ^0.5.1
  collection: ^1.19.1
  json_annotation: ^4.9.0
  phone_numbers_parser: ^9.0.11
  country_code_picker: ^3.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/

get_cli:
  sub_folder: false
