// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'company_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Company _$CompanyFromJson(Map<String, dynamic> json) => Company(
  mNameChinese: Functions.asString(json['mName_Chinese']),
  mTel: Functions.asString(json['mTel']),
  mFax: Functions.asString(json['mFax']),
  mAddress: Functions.asString(json['mAddress']),
  mEMail: Functions.asString(json['mEMail']),
  mLogoPath: Functions.asString(json['mLogoPath']),
  mWebSite: Functions.asString(json['mWebSite']),
  mNameEnglish: Functions.asString(json['mName_English']),
  tCompanyId: Functions.asString(json['T_Company_ID']),
  mStockAdjustmentInPreFix: Functions.asString(
    json['mStock_Adjustment_In_PreFix'],
  ),
  mStockAdjustmentInSubFix: Functions.asString(
    json['mStock_Adjustment_In_SubFix'],
  ),
  mInitStockAdjustmentInNo: Functions.asString(
    json['mInit_Stock_Adjustment_In_No'],
  ),
  mStockInternalPreFix: Functions.asString(json['mStock_Internal_PreFix']),
  mStockInternalSubFix: Functions.asString(json['mStock_Internal_SubFix']),
  mInitStockInternalNo: Functions.asString(json['mInit_Stock_Internal_No']),
  mSupplierInvoiceInPreFix: Functions.asString(
    json['mSupplier_Invoice_In_PreFix'],
  ),
  mSupplierInvoiceInSubFix: Functions.asString(
    json['mSupplier_Invoice_In_SubFix'],
  ),
  mInitSupplierInvoiceInNo: Functions.asString(
    json['mInit_Supplier_Invoice_In_No'],
  ),
  mStockAdjustmentOutPreFix: Functions.asString(
    json['mStock_Adjustment_Out_PreFix'],
  ),
  mStockAdjustmentOutSubFix: Functions.asString(
    json['mStock_Adjustment_Out_SubFix'],
  ),
  mInitStockAdjustmentOutNo: Functions.asString(
    json['mInit_Stock_Adjustment_Out_No'],
  ),
  mConsignmentInPreFix: Functions.asString(json['mConsignment_In_PreFix']),
  mConsignmentInSubFix: Functions.asString(json['mConsignment_In_SubFix']),
  mInitConsignmentInNo: Functions.asString(json['mInit_Consignment_In_No']),
  mConsignmentOutPreFix: Functions.asString(json['mConsignment_Out_PreFix']),
  mConsignmentOutSubFix: Functions.asString(json['mConsignment_Out_SubFix']),
  mInitConsignmentOutNo: Functions.asString(json['mInit_Consignment_Out_No']),
  mTradingInvoicePreFix: Functions.asString(json['mTrading_Invoice_PreFix']),
  mTradingInvoiceSubFix: Functions.asString(json['mTrading_Invoice_SubFix']),
  mInitTradingInvoiceNo: Functions.asString(json['mInit_Trading_Invoice_No']),
  mCustomerPreFix: Functions.asString(json['mCustomer_PreFix']),
  mCustomerSubFix: Functions.asString(json['mCustomer_SubFix']),
  mUpdateUrl: Functions.asString(json['mUpdate_URL']),
  mUpdateVersion: Functions.asString(json['mUpdate_Version']),
  mDefaultCustomer: Functions.asString(json['mDefault_Customer']),
  mTradingInvoiceTerms: Functions.asString(json['mTrading_Invoice_Terms']),
  mSupplierInvoiceTerms: Functions.asString(json['mSupplier_Invoice_Terms']),
  mExtend: Functions.asString(json['mExtend']),
  mFtpServer: json['mFtp_Server, fromJson: Functions.asString'] as String?,
  mFtpUser: Functions.asString(json['mFtp_User']),
  mFtpPassword: Functions.asString(json['mFtp_Password']),
  mArCredItCode: Functions.asString(json['mAR_CREDIt_code']),
  mApDebItCode: Functions.asString(json['mAP_DEBIt_code']),
  mElectronicOrderingPreFix: Functions.asString(
    json['mElectronic_Ordering_PreFix'],
  ),
  mElectronicOrderingSubFix: Functions.asString(
    json['mElectronic_Ordering_SubFix'],
  ),
  mInitElectronicOrderingNo: Functions.asString(
    json['mInit_electronic_ordering_no'],
  ),
  mQrUrl: Functions.asString(json['mQRUrl']),
  cloudPrintUser: Functions.asString(json['cloudPrintUser']),
  cloudPrintKey: Functions.asString(json['cloudPrintKey']),
  invoicePrinter: Functions.asString(json['invoicePrinter']),
  upperMenuPrinter: Functions.asString(json['upperMenuPrinter']),
  isPrintPrice: Functions.asString(json['isPrintPrice']),
  mTakeawayInformation: Functions.asString(json['mTakeaway_Information']),
  mFtpList: Functions.asString(json['mFtp_list']),
  mKiosk2: Functions.asString(json['mKiosk2']),
  mKiosk3: Functions.asString(json['mKiosk3']),
  isCloudPrinter: Functions.asString(json['isCloudPrinter']),
  atuoFoodList: Functions.asString(json['atuo_food_list']),
  takeawayPrinter: Functions.asString(json['takeaway_printer']),
  taAutoPrint: Functions.asString(json['ta_auto_print']),
  mNotify: Functions.asString(json['mNotify']),
  mTableDisplay: Functions.asString(json['mTableDisplay']),
  mKPayId: Functions.asString(json['mKPayID']),
  mKPaySecret: Functions.asString(json['mKPaySecret']),
  isShowPickUp: Functions.asString(json['isShowPickUP']),
  mPickupOnly: Functions.asString(json['mPickupOnly']),
  onlinePayment: Functions.asString(json['online_payment']),
  bbmslMerchantId: Functions.asString(json['BBMSL_Merchant_ID']),
  bbmslPrivateKey: Functions.asString(json['BBMSL_Private_Key']),
  webVersionDiscountAmt: Functions.asString(json['Web_version_discount_amt']),
  webVersionServiceFee: Functions.asString(json['Web_version_service_fee']),
  webVersionDiscount: Functions.asString(json['Web_version_discount']),
  precisionToDecimalPlaces: Functions.asString(
    json['Precision_to_decimal_places'],
  ),
  accurateMethod: Functions.asString(json['Accurate_method']),
  mPointDisplay: Functions.asString(json['mPointDisplay']),
  firebaseConfig: Functions.asString(json['firebaseConfig']),
  bbmslProductEnv: Functions.asString(json['bbmsl_product_env']),
  mQtyLimit: Functions.asString(json['mQty_limit']),
  sunmiPrinter: Functions.asString(json['sunmi_printer']),
  mFontSize: Functions.asString(json['mFont_size']),
  mPaymentPlatform: Functions.asString(json['mPayment_Platform']),
  mWonderBusinessId: Functions.asString(json['mWonder_BusinessID']),
  mWonderAppSlug: Functions.asString(json['mWonder_AppSlug']),
  mWonderAppKey: Functions.asString(json['mWonder_AppKey']),
  mWonderPoiid: Functions.asString(json['mWonder_POIID']),
  mWonderAuth: Functions.asString(json['mWonder_Auth']),
  mNotificationEmail: Functions.asString(json['mNotification_Email']),
  mSelfLogin: Functions.asString(json['mSelf_login']),
  autoPrintStation: Functions.asString(json['auto_print_station']),
  mAirPrint: Functions.asString(json['mAirPrint']),
  yeahpayAppid: Functions.asString(json['yeahpay_appid']),
  yeahpayMerchantid: Functions.asString(json['yeahpay_merchantid']),
  yeahpayPublicKey: Functions.asString(json['yeahpay_public_key']),
  yeahpayClientPrivateKey: Functions.asString(
    json['yeahpay_client_private_key'],
  ),
  loginMethod: Functions.asString(json['Login_method']),
  mBackupPrintingTime: Functions.asString(json['mBackup_printing_time']),
  appHome: Functions.asString(json['app_home']),
  mQrremark: Functions.asString(json['mQrremark']),
);

Map<String, dynamic> _$CompanyToJson(Company instance) => <String, dynamic>{
  'mName_Chinese': instance.mNameChinese,
  'mTel': instance.mTel,
  'mFax': instance.mFax,
  'mAddress': instance.mAddress,
  'mEMail': instance.mEMail,
  'mLogoPath': instance.mLogoPath,
  'mWebSite': instance.mWebSite,
  'mName_English': instance.mNameEnglish,
  'T_Company_ID': instance.tCompanyId,
  'mStock_Adjustment_In_PreFix': instance.mStockAdjustmentInPreFix,
  'mStock_Adjustment_In_SubFix': instance.mStockAdjustmentInSubFix,
  'mInit_Stock_Adjustment_In_No': instance.mInitStockAdjustmentInNo,
  'mStock_Internal_PreFix': instance.mStockInternalPreFix,
  'mStock_Internal_SubFix': instance.mStockInternalSubFix,
  'mInit_Stock_Internal_No': instance.mInitStockInternalNo,
  'mSupplier_Invoice_In_PreFix': instance.mSupplierInvoiceInPreFix,
  'mSupplier_Invoice_In_SubFix': instance.mSupplierInvoiceInSubFix,
  'mInit_Supplier_Invoice_In_No': instance.mInitSupplierInvoiceInNo,
  'mStock_Adjustment_Out_PreFix': instance.mStockAdjustmentOutPreFix,
  'mStock_Adjustment_Out_SubFix': instance.mStockAdjustmentOutSubFix,
  'mInit_Stock_Adjustment_Out_No': instance.mInitStockAdjustmentOutNo,
  'mConsignment_In_PreFix': instance.mConsignmentInPreFix,
  'mConsignment_In_SubFix': instance.mConsignmentInSubFix,
  'mInit_Consignment_In_No': instance.mInitConsignmentInNo,
  'mConsignment_Out_PreFix': instance.mConsignmentOutPreFix,
  'mConsignment_Out_SubFix': instance.mConsignmentOutSubFix,
  'mInit_Consignment_Out_No': instance.mInitConsignmentOutNo,
  'mTrading_Invoice_PreFix': instance.mTradingInvoicePreFix,
  'mTrading_Invoice_SubFix': instance.mTradingInvoiceSubFix,
  'mInit_Trading_Invoice_No': instance.mInitTradingInvoiceNo,
  'mCustomer_PreFix': instance.mCustomerPreFix,
  'mCustomer_SubFix': instance.mCustomerSubFix,
  'mUpdate_URL': instance.mUpdateUrl,
  'mUpdate_Version': instance.mUpdateVersion,
  'mDefault_Customer': instance.mDefaultCustomer,
  'mTrading_Invoice_Terms': instance.mTradingInvoiceTerms,
  'mSupplier_Invoice_Terms': instance.mSupplierInvoiceTerms,
  'mExtend': instance.mExtend,
  'mFtp_Server, fromJson: Functions.asString': instance.mFtpServer,
  'mFtp_User': instance.mFtpUser,
  'mFtp_Password': instance.mFtpPassword,
  'mAR_CREDIt_code': instance.mArCredItCode,
  'mAP_DEBIt_code': instance.mApDebItCode,
  'mElectronic_Ordering_PreFix': instance.mElectronicOrderingPreFix,
  'mElectronic_Ordering_SubFix': instance.mElectronicOrderingSubFix,
  'mInit_electronic_ordering_no': instance.mInitElectronicOrderingNo,
  'mQRUrl': instance.mQrUrl,
  'cloudPrintUser': instance.cloudPrintUser,
  'cloudPrintKey': instance.cloudPrintKey,
  'invoicePrinter': instance.invoicePrinter,
  'upperMenuPrinter': instance.upperMenuPrinter,
  'isPrintPrice': instance.isPrintPrice,
  'mTakeaway_Information': instance.mTakeawayInformation,
  'mFtp_list': instance.mFtpList,
  'mKiosk2': instance.mKiosk2,
  'mKiosk3': instance.mKiosk3,
  'isCloudPrinter': instance.isCloudPrinter,
  'atuo_food_list': instance.atuoFoodList,
  'takeaway_printer': instance.takeawayPrinter,
  'ta_auto_print': instance.taAutoPrint,
  'mNotify': instance.mNotify,
  'mTableDisplay': instance.mTableDisplay,
  'mKPayID': instance.mKPayId,
  'mKPaySecret': instance.mKPaySecret,
  'isShowPickUP': instance.isShowPickUp,
  'mPickupOnly': instance.mPickupOnly,
  'online_payment': instance.onlinePayment,
  'BBMSL_Merchant_ID': instance.bbmslMerchantId,
  'BBMSL_Private_Key': instance.bbmslPrivateKey,
  'Web_version_discount_amt': instance.webVersionDiscountAmt,
  'Web_version_service_fee': instance.webVersionServiceFee,
  'Web_version_discount': instance.webVersionDiscount,
  'Precision_to_decimal_places': instance.precisionToDecimalPlaces,
  'Accurate_method': instance.accurateMethod,
  'mPointDisplay': instance.mPointDisplay,
  'firebaseConfig': instance.firebaseConfig,
  'bbmsl_product_env': instance.bbmslProductEnv,
  'mQty_limit': instance.mQtyLimit,
  'sunmi_printer': instance.sunmiPrinter,
  'mFont_size': instance.mFontSize,
  'mPayment_Platform': instance.mPaymentPlatform,
  'mWonder_BusinessID': instance.mWonderBusinessId,
  'mWonder_AppSlug': instance.mWonderAppSlug,
  'mWonder_AppKey': instance.mWonderAppKey,
  'mWonder_POIID': instance.mWonderPoiid,
  'mWonder_Auth': instance.mWonderAuth,
  'mNotification_Email': instance.mNotificationEmail,
  'mSelf_login': instance.mSelfLogin,
  'auto_print_station': instance.autoPrintStation,
  'mAirPrint': instance.mAirPrint,
  'yeahpay_appid': instance.yeahpayAppid,
  'yeahpay_merchantid': instance.yeahpayMerchantid,
  'yeahpay_public_key': instance.yeahpayPublicKey,
  'yeahpay_client_private_key': instance.yeahpayClientPrivateKey,
  'Login_method': instance.loginMethod,
  'mBackup_printing_time': instance.mBackupPrintingTime,
  'app_home': instance.appHome,
  'mQrremark': instance.mQrremark,
};
